# Generated by Django 4.2.4 on 2023-08-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='Item',
        ),
    ]
