# Generated by Django 4.2.4 on 2023-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brandmodel',
            field=models.CharField(default='apple', max_length=100),
        ),
    ]
